### ISSUE TITLE
logのaggregator(?)のリポジトリ

### ISSUE THREAD

**Issue by bananaumai** [lvs-tech-club/confl-access-logger#2]
このリポジトリと別にしますか？
LAは一緒のリポジトリになってたと思いますがどうしましょう？
Goで作ろうと思っています。

**Comment by taise** [comment]
動作確認のために一緒にしちゃっていましたが別で良いと思います。
GoでGAE or [Container Engine](https://cloud.google.com/container-engine/?hl=ja)か、という感じでしょうか。

jsの配信どうしましょうかね。
AWS Cloudfrontに、直接対応するものはGCPにはなくGAEになるみたいです。
[PublicCloud対比表(AWS/Azure/GCP/Softlayer)](http://qiita.com/nntsugu/items/2428a15e67de42d66947)

**Comment by bananaumai** [comment]
そうですね、個人的にも別が良い気がします！
別にしちゃいましょう！
とりあえずGAEで動かして、後々Container Engineとかが楽っすかね。そこはまだ考えてなかったです。
一旦本件はクローズします。
